"""Configuration for Studia backend."""

OLLAMA_MODEL = "deepseek-r1:8b"
OLLAMA_BASE_URL = "http://localhost:11434"
WHISPER_MODEL_SIZE = "base.en"
WHISPER_DEVICE = "cpu"
SAMPLE_RATE = 16000
TTS_ENABLED = True
TTS_RATE = 160
LOG_SESSIONS = True
MAX_HISTORY_EXCHANGES = 30
RESEARCH_MAX_SOURCES = 8
RESEARCH_CACHE_DAYS = 7
BACKEND_HOST = "127.0.0.1"
BACKEND_PORT = 8000
